class ProjectMacros:
    INSTALL_INDEX_SVN = 1
    INSTALL_INDEX_P4 = 2
    INSTALL_INDEX_VS = 3
    INSTALL_INDEX_VS_CODE = 4

    TOOLS_STATE_NEED_INSTALL = 0
    TOOLS_STATE_ALREADY_INSTALL = 1
    TOOLS_STATE_INSTALLING = 2
    TOOLS_STATE_DOWNLOADING = 3
    TOOLS_STATE_DOWNLOADED = 4